<?php
/**
 * Created by PhpStorm.
 * User: Трик
 * Date: 10.07.2016
 * Time: 11:30
 */

require_once "global_class.php";

class Post extends GlobalClass
{
    public function __construct($db)
    {
        parent::__construct("post", $db);
    }

    public function addPost($new_values)
    {
        return $this->add($new_values); // TODO: Change the autogenerated stub
    }

    public function editPost($id, $title, $text, $text_desc, $section, $on_main, $type_img) {
        return $this->edit($id, array("title" => $title, "text" => $text, "text_desc" => $text_desc, "section_id" => $section, "on_main" => $on_main, "type_img" => $type_img));
    }
    
    public function getAllOnMain() {
        return $this->getAllOnField("on_main", 1);
    }

    public function getAllFaq() {
        return $this->getAllOnField("section_id", 5);
    }

    public function deletePost($id)
    {
        return $this->delete($id); // TODO: Change the autogenerated stub
    }

    public function getLast() {
        return $this->getLastIDIn();
    }
}